version: "2.1"
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
#    environment:
#      - RABBITMQ_DEFAULT_USER=rmuser
#      - RABBITMQ_DEFAULT_PASS=rmpassword
#      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq_logs:/var/log/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - ./redisdata:/data
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_USER_PASSWORD}
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  pg_data: