version: "2.1"

services:
  redis:
    image: redis:latest
    container_name: redis_container1
    environment:
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - ./redisdata:/data
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_USER_PASSWORD}

  postgres:
    image: postgres:latest
    container_name: postgres_db1
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app1
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://${DB_USER}:${DB_PASS}@postgres:5432/${DB_NAME}
      REDIS_URL: redis://default:${REDIS_USER_PASSWORD}@redis:6379/0
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  pg_data:
