version: "2.1"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exchange_app
    command: >
      sh -c "alembic upgrade head &&
             gunicorn src.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 & python3 src/tasks/background_task.py"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      REDIS_USER_PASSWORD: ${REDIS_USER_PASSWORD}
      REDIS_HOST: redis
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
  redis:
    image: redis:latest
    container_name: redis_container1
    environment:
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - ./redisdata:/data
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_USER_PASSWORD}

  postgres:
    image: postgres:latest
    container_name: postgres_db1
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pg_data:
