"""add ticker in tradelog

Revision ID: 7aacc893b935
Revises: f0df031a79c6
Create Date: 2025-05-21 22:29:24.243696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aacc893b935'
down_revision: Union[str, None] = 'f0df031a79c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_log', sa.Column('ticker', sa.String(length=10), nullable=False))
    op.create_index(op.f('ix_trade_log_ticker'), 'trade_log', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_log_ticker'), table_name='trade_log')
    op.drop_column('trade_log', 'ticker')
    # ### end Alembic commands ###
