"""fix filled

Revision ID: a13f8d7ff5a3
Revises: e0fb9214f46a
Create Date: 2025-05-18 21:32:54.308562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a13f8d7ff5a3'
down_revision: Union[str, None] = 'e0fb9214f46a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'filled',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'filled',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
