"""Add frozen balance user RUB

Revision ID: e0fb9214f46a
Revises: 7cffd20673d6
Create Date: 2025-05-18 13:51:12.654004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0fb9214f46a'
down_revision: Union[str, None] = '7cffd20673d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('frozen_balance', sa.Float(), nullable=False))
    op.create_index(op.f('ix_users_frozen_balance'), 'users', ['frozen_balance'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_frozen_balance'), table_name='users')
    op.drop_column('users', 'frozen_balance')
    # ### end Alembic commands ###
