"""add unique apikey

Revision ID: e718fe8f8da9
Revises: 7aacc893b935
Create Date: 2025-05-31 23:22:48.764380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e718fe8f8da9'
down_revision: Union[str, None] = '7aacc893b935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_api_key', table_name='users')
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.create_index('ix_users_api_key', 'users', ['api_key'], unique=False)
    # ### end Alembic commands ###
