"""fix user balanc

Revision ID: f0df031a79c6
Revises: 6c4e31c72319
Create Date: 2025-05-19 16:27:16.568913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0df031a79c6'
down_revision: Union[str, None] = '6c4e31c72319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_balance', table_name='users')
    op.drop_index('ix_users_frozen_balance', table_name='users')
    op.drop_column('users', 'frozen_balance')
    op.drop_column('users', 'balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('frozen_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.create_index('ix_users_frozen_balance', 'users', ['frozen_balance'], unique=False)
    op.create_index('ix_users_balance', 'users', ['balance'], unique=False)
    # ### end Alembic commands ###
